# Generated by Django 5.0.3 on 2024-03-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='publication_date',
            field=models.DateTimeField(),
        ),
    ]
